### ISSUE TITLE
Impossible to use watches on distributed application

### ISSUE THREAD

**Issue by melekhove** [eclipse-4diac/4diac-ide#799]
Steps to reproduce:
-  Create simple distributed application as described in [Tutorial Step 2](https://github.com/eclipse-4diac/4diac-documentation/blob/main/src/tutorials/distribute4diac.adoc)
- Select all devices on the application tab and toggle Watches
- Start two FORTE instances
- Deploy to both instances
- Right Click on any device in system configuration, select Monitor As/Monitor
- Observe the error dialog

Here is the stack trace
```
!STACK 0
java.lang.IllegalStateException: Duplicate key TestTwoDevicesApp.E_SR (
attempted merging values org.eclipse.fordiac.ide.deployment.debug.watch.FBNetworkElementWatch@12169ca9 
and org.eclipse.fordiac.ide.deployment.debug.watch.FBNetworkElementWatch@12169ca9)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1778)
	at java.base/java.util.concurrent.ConcurrentSkipListMap$EntrySpliterator.forEachRemaining(ConcurrentSkipListMap.java:3360)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1803)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugTarget.updateWatches(DeploymentDebugTarget.java:210)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.addWatch(DeploymentDebugDevice.java:256)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.breakpointAdded(DeploymentDebugDevice.java:224)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.connect(DeploymentDebugDevice.java:129)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugTarget.doConnect(DeploymentDebugTarget.java:125)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugTarget.lambda$2(DeploymentDebugTarget.java:100)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```
I know the reason of the issue and will try to provide PR soon.

**Comment by mx990** [comment]
Thank you again for looking into this!
