### ISSUE TITLE
Impossible to export FB using FORTE Lua exporter

### ISSUE THREAD

**Issue by melekhove** [eclipse-4diac/4diac-ide#809]
Steps to reproduce:

- create new FB (composite for example)
- Try to export using '4diac IDE type Export'
- Select exporter 'FORTE Lua'
- Observe the following exception

```
!MESSAGE InvocationTargetException
!STACK 0
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:396)
	...
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
Caused by: java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.EObject.eClass()" because "type" is null
	at org.eclipse.fordiac.ide.export.forte_lua.ForteLuaExportFilter.export(ForteLuaExportFilter.java:68)
	at org.eclipse.fordiac.ide.export.ui.wizard.FordiacExportWizard$Exporter.exportElement(FordiacExportWizard.java:195)
	at org.eclipse.fordiac.ide.export.ui.wizard.FordiacExportWizard$Exporter.run(FordiacExportWizard.java:151)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Root exception:
java.lang.NullPointerException: Cannot invoke "org.eclipse.emf.ecore.EObject.eClass()" because "type" is null
	at org.eclipse.fordiac.ide.export.forte_lua.ForteLuaExportFilter.export(ForteLuaExportFilter.java:68)
	at org.eclipse.fordiac.ide.export.ui.wizard.FordiacExportWizard$Exporter.exportElement(FordiacExportWizard.java:195)
	at org.eclipse.fordiac.ide.export.ui.wizard.FordiacExportWizard$Exporter.run(FordiacExportWizard.java:151)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
```

Using code similar to this https://github.com/eclipse-4diac/4diac-ide/blob/ec93bcfe057d4e4f6374cce77eb13690db36ebf3/plugins/org.eclipse.fordiac.ide.export/src/org/eclipse/fordiac/ide/export/TemplateExportFilter.java#L111-L122 helps

**Comment by azoitl** [comment]
The lua exporter was never intended to be accessible from the ui. Furhtemore it is currently severly broken therefore I deadicated it for the 3.0 release.
